#include "c_emit_internal.h"

#include <stdlib.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Helpers                                                              */
/* ------------------------------------------------------------------ */

static bool emit_file_header(FILE *out) {
    fputs("/* Generated by the calynda compiler. */\n", out);
    fputs("#include <stdbool.h>\n", out);
    fputs("#include <stddef.h>\n", out);
    fputs("#include <stdint.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include \"calynda_runtime.h\"\n", out);
    fputc('\n', out);
    return true;
}

/* ------------------------------------------------------------------ */
/* Forward-declare all globals, start/boot functions, and externs      */
/* ------------------------------------------------------------------ */

static bool emit_forward_decls(CEmitContext *ctx, const HirProgram *program) {
    FILE   *out = ctx->out;
    size_t  i;

    /* Emit import package bindings */
    for (i = 0; i < program->import_count; i++) {
        const HirNamedSymbol *imp = &program->imports[i];
        if (imp->name) {
            fprintf(out, "#define __cal_%s "
                         "((CalyndaRtWord)(uintptr_t)&__calynda_pkg_%s)\n",
                    imp->name, imp->name);
        }
    }
    if (program->import_count > 0) {
        fputc('\n', out);
    }

    /* Emit extern C forward declarations first */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];
        size_t j;

        if (!decl || decl->kind != HIR_TOP_LEVEL_EXTERN) {
            continue;
        }

        /* extern <return_type> <name>(<param_types>); */
        fputs("extern CalyndaRtWord ", out);
        fputs(decl->as.extern_decl.name, out);
        fputs("(", out);
        for (j = 0; j < decl->as.extern_decl.parameters.count; j++) {
            if (j > 0) {
                fputs(", ", out);
            }
            if (decl->as.extern_decl.parameters.items[j].is_varargs) {
                fputs("...", out);
            } else {
                fputs("CalyndaRtWord", out);
                if (decl->as.extern_decl.parameters.items[j].name) {
                    fputc(' ', out);
                    c_emit_safe_name(out, decl->as.extern_decl.parameters.items[j].name);
                }
            }
        }
        if (decl->as.extern_decl.parameters.count == 0) {
            fputs("void", out);
        }
        fputs(");\n", out);
    }

    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (!decl) {
            continue;
        }
        if (decl->kind == HIR_TOP_LEVEL_BINDING) {
            fputs("static CalyndaRtWord ", out);
            c_emit_global_name(out, decl->as.binding.name);
            fputs(";\n", out);
        }
    }

    /* Forward-declare the start function if present */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (decl && decl->kind == HIR_TOP_LEVEL_START) {
            fputs("static CalyndaRtWord __calynda_start(CalyndaRtWord __calynda_argv);\n", out);
            break;
        }
        if (decl && decl->kind == HIR_TOP_LEVEL_BOOT) {
            fputs("static void __calynda_boot(void);\n", out);
            break;
        }
    }

    fputc('\n', out);
    return true;
}

/* ------------------------------------------------------------------ */
/* Emit global initialisation function                                  */
/* ------------------------------------------------------------------ */

static bool emit_init_globals(CEmitContext *ctx, const HirProgram *program) {
    FILE   *out = ctx->out;
    size_t  i;
    bool    any = false;

    /* Check if there are any initialised bindings */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (decl && decl->kind == HIR_TOP_LEVEL_BINDING &&
            decl->as.binding.initializer) {
            any = true;
            break;
        }
    }

    if (!any) {
        return true;
    }

    fputs("static void __calynda_init_globals(void)\n{\n", out);

    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (!decl || decl->kind != HIR_TOP_LEVEL_BINDING) {
            continue;
        }
        if (!decl->as.binding.initializer) {
            continue;
        }

        fputs("    ", out);
        c_emit_global_name(out, decl->as.binding.name);
        fputs(" = ", out);
        if (!c_emit_expr(ctx, decl->as.binding.initializer)) {
            return false;
        }
        fputs(";\n", out);
    }

    fputs("}\n\n", out);
    return true;
}

/* ------------------------------------------------------------------ */
/* Emit the start function body                                          */
/* ------------------------------------------------------------------ */

static bool emit_start_function(CEmitContext *ctx, const HirProgram *program) {
    FILE   *out = ctx->out;
    size_t  i;

    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (!decl || decl->kind != HIR_TOP_LEVEL_START) {
            continue;
        }

        fputs("static CalyndaRtWord __calynda_start(CalyndaRtWord __calynda_argv)\n{\n", out);

        /* Bind parameter name (the args array) */
        if (decl->as.start.parameters.count > 0) {
            fprintf(out, "    CalyndaRtWord ");
            c_emit_global_name(out, decl->as.start.parameters.items[0].name);
            fputs(" = __calynda_argv;\n", out);
        } else {
            fputs("    (void)__calynda_argv;\n", out);
        }

        if (!c_emit_block(ctx, decl->as.start.body)) {
            return false;
        }

        fputs("    return (CalyndaRtWord)0;\n", out);
        fputs("}\n\n", out);
        return true;
    }

    /* No start decl — emit a trivial one (only if no boot decl either) */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];
        if (decl && decl->kind == HIR_TOP_LEVEL_BOOT) {
            return true; /* boot handles its own entry */
        }
    }

    fputs("static CalyndaRtWord __calynda_start(CalyndaRtWord __calynda_argv)\n{\n", out);
    fputs("    (void)__calynda_argv;\n", out);
    fputs("    return (CalyndaRtWord)0;\n", out);
    fputs("}\n\n", out);
    return true;
}

/* ------------------------------------------------------------------ */
/* Emit the boot function body                                           */
/* ------------------------------------------------------------------ */

static bool emit_boot_function(CEmitContext *ctx, const HirProgram *program) {
    FILE   *out = ctx->out;
    size_t  i;

    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (!decl || decl->kind != HIR_TOP_LEVEL_BOOT) {
            continue;
        }

        fputs("static void __calynda_boot(void)\n{\n", out);

        ctx->is_boot_context = true;
        if (!c_emit_block(ctx, decl->as.boot.body)) {
            ctx->is_boot_context = false;
            return false;
        }
        ctx->is_boot_context = false;

        fputs("}\n\n", out);
        return true;
    }

    return true; /* no boot decl is fine */
}

/* ------------------------------------------------------------------ */
/* Emit main() or boot entry wrapper                                     */
/* ------------------------------------------------------------------ */

static bool emit_main(CEmitContext *ctx, bool has_init_globals, bool has_boot) {
    FILE *out = ctx->out;

    /*
     * Emit the entry point as calynda_program_main().  On the host target
     * (no external main wrapper) a small #ifndef block generates the real
     * main() that simply delegates to calynda_program_main().  On Wii/GC
     * targets the calynda_wii_main.o object provides main() and calls
     * calynda_program_main() after initialising the console.
     */
    if (has_boot) {
        fputs("int calynda_program_main(int argc, char **argv)\n{\n", out);
        fputs("    (void)argc; (void)argv;\n", out);
        if (has_init_globals) {
            fputs("    __calynda_init_globals();\n", out);
        }
        fputs("    __calynda_boot();\n", out);
        fputs("    return 0;\n", out);
        fputs("}\n\n", out);
    } else {
        fputs("int calynda_program_main(int argc, char **argv)\n{\n", out);
        if (has_init_globals) {
            fputs("    __calynda_init_globals();\n", out);
        }
        fputs("    return calynda_rt_start_process(__calynda_start, argc, argv);\n", out);
        fputs("}\n\n", out);
    }

    /* Fallback main() for host builds where no external wrapper is linked. */
    fputs("#ifndef CALYNDA_WII_BUILD\n", out);
    fputs("int main(int argc, char **argv)\n{\n", out);
    fputs("    return calynda_program_main(argc, argv);\n", out);
    fputs("}\n", out);
    fputs("#endif\n", out);

    return true;
}

/* ------------------------------------------------------------------ */
/* Public entry point                                                   */
/* ------------------------------------------------------------------ */

bool c_emit_program(FILE *out, const HirProgram *program) {
    return c_emit_program_with_file(out, program, NULL);
}

bool c_emit_program_with_file(FILE *out, const HirProgram *program,
                              const char *source_file) {
    CEmitContext ctx;
    bool         has_init_globals = false;
    bool         has_boot = false;
    size_t       i;

    if (!out || !program) {
        return false;
    }

    /* Initialise context */
    memset(&ctx, 0, sizeof(ctx));
    ctx.out = out;
    ctx.source_file = source_file;

    /* Pre-scan to collect all lambdas */
    if (!c_emit_prescan_program(&ctx, program)) {
        free(ctx.lambdas);
        return false;
    }

    /* Check if we have a boot decl */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];
        if (decl && decl->kind == HIR_TOP_LEVEL_BOOT) {
            has_boot = true;
            break;
        }
    }

    /* Emit file header */
    if (!emit_file_header(out)) {
        free(ctx.lambdas);
        return false;
    }

    /* Emit forward declarations */
    if (!emit_forward_decls(&ctx, program)) {
        free(ctx.lambdas);
        return false;
    }

    /* Emit lambda C functions (before globals that reference them) */
    if (!c_emit_lambda_functions(&ctx)) {
        free(ctx.lambdas);
        return false;
    }

    /* Check if we need an init_globals */
    for (i = 0; i < program->top_level_count; i++) {
        const HirTopLevelDecl *decl = program->top_level_decls[i];

        if (decl && decl->kind == HIR_TOP_LEVEL_BINDING &&
            decl->as.binding.initializer) {
            has_init_globals = true;
            break;
        }
    }

    /* Emit global initialiser */
    if (!emit_init_globals(&ctx, program)) {
        free(ctx.lambdas);
        return false;
    }

    /* Emit start or boot function */
    if (has_boot) {
        if (!emit_boot_function(&ctx, program)) {
            free(ctx.lambdas);
            return false;
        }
    } else {
        if (!emit_start_function(&ctx, program)) {
            free(ctx.lambdas);
            return false;
        }
    }

    /* Emit main */
    if (!emit_main(&ctx, has_init_globals, has_boot)) {
        free(ctx.lambdas);
        return false;
    }

    free(ctx.lambdas);
    return true;
}
