/*
 * Package + import header (req 8.1) and extern-block emitter (req 8.2).
 */
#include "emit_cal_internal.h"
#include "cli/demangle.h"

#include <ctype.h>
#include <string.h>

int emit_package_header(EmitFile *ef, const char *package,
                        const char *const *imports, size_t n_imports) {
    if (emit_linef(ef, "# Auto-generated by calynda decompiler (req 8).") < 0)
        return -1;
    emit_linef(ef, "# Edits in this file will be overwritten on re-emit.");
    emit_linef(ef, "");
    emit_linef(ef, "package %s", package);
    if (n_imports > 0) {
        emit_linef(ef, "");
        for (size_t i = 0; i < n_imports; i++)
            emit_linef(ef, "import %s", imports[i]);
    }
    emit_linef(ef, "");
    return 0;
}

/* Shared policy: legal Calynda identifier characters. */
void emit_safe_ident(const char *raw, char *out, size_t n) {
    size_t k = 0;
    for (size_t i = 0; raw[i] && k + 1 < n; i++) {
        unsigned char c = (unsigned char)raw[i];
        if (isalnum(c) || c == '_') out[k++] = (char)c;
        else if (c == ':' && raw[i + 1] == ':') { out[k++] = '_'; i++; }
        else if (c == '.' || c == '-' || c == ' ') out[k++] = '_';
        /* otherwise drop */
    }
    if (k == 0 && n > 0) out[k++] = '_';
    if (k < n) out[k] = '\0';
}

/* Top-level namespace component (before "::") — that becomes the
 * target file basename for the function. Falls back to "main". */
void emit_symbol_package(const char *raw, char *out, size_t n) {
    /* Strip any leading __ / __cl / typeinfo / CodeWarrior decoration. */
    const char *p = raw;
    while (*p == '_') p++;

    /* C++ qualifier: "nw4r::util::Foo" -> "nw4r". */
    const char *colon = strstr(p, "::");
    if (colon) {
        size_t len = (size_t)(colon - p);
        if (len >= n) len = n - 1;
        memcpy(out, p, len);
        out[len] = '\0';
        /* Demangler maps EGG -> egg; mirror that here. */
        for (size_t i = 0; out[i]; i++)
            if (out[i] >= 'A' && out[i] <= 'Z') out[i] |= 0x20;
        return;
    }

    /* Mangled CodeWarrior F-form: "Foo__3BarFv" -> "Bar". */
    const char *dd = strstr(raw, "__");
    if (dd && isdigit((unsigned char)dd[2])) {
        const char *q = dd + 2;
        int len = 0;
        while (isdigit((unsigned char)*q)) { len = len * 10 + (*q - '0'); q++; }
        if (len > 0 && q[0] != '\0') {
            size_t cp = (size_t)len < n ? (size_t)len : n - 1;
            memcpy(out, q, cp);
            out[cp] = '\0';
            for (size_t i = 0; out[i]; i++)
                if (out[i] >= 'A' && out[i] <= 'Z') out[i] |= 0x20;
            return;
        }
    }

    snprintf(out, n, "main");
}

int emit_extern_block(EmitFile *ef, const Externs *ex, const char *module) {
    if (!ex || !ex->count) return 0;
    int emitted = 0;
    for (size_t i = 0; i < ex->count; i++) {
        const ExternSymbol *s = &ex->entries[i];
        if (module && *module && strcmp(s->module, module) != 0) continue;
        const char *n = s->name[0] ? s->name : s->raw_name;
        if (!emitted) {
            emit_linef(ef, "# --- extern declarations (req 8.2) ---");
        }
        emit_linef(ef, "# 0x%08x  %s%s", s->vaddr, s->raw_name,
                   s->is_variadic ? "  (variadic)" : "");
        emit_linef(ef, "extern %s %s", n, s->cal_sig);
        emitted++;
    }
    if (emitted) emit_linef(ef, "");
    return emitted;
}
